input: songs-ml-10pct.csv
output: output/genre_classification/
vectorizer:
  name: TfidfVectorizer
  module: sklearn.feature_extraction.text
  params:
#    min_df: 0.3
#    max_df: 0.9
    min_df: 0.01
    max_df: 0.9
    max_features: 1000
    sublinear_tf: false
resampler:
  name: MLSOL
  module: mlsol
  params:
    perc_gen_instances: 0.3
    k: 5
    random_state: 0
models:
#  -
#    name: LogisticRegression
#    module: sklearn.linear_model
#    params:
#      solver: newton-cg
#      C: 0.1
#      max_iter: 1000
#      random_state: 0
#    threshold:
#      - 0.18
#      - 0.34
#      - 0.18
#      - 0.21
#      - 0.20
  -
    name: BernoulliNB
    module: sklearn.naive_bayes
    params:
      alpha:
        - 1.0
    threshold:
      - 0.041
      - 0.48
      - 0.048
      - 0.035
      - 0.099
#  -
#    name: RandomForestClassifier
#    module: sklearn.ensemble
#    params:
#      n_estimators: 300
#      max_depth: 10
#      max_features: 'auto'
#      min_samples_leaf: 1
#      min_samples_split: 2
#      bootstrap: true
#      n_jobs: -1
#      random_state: 0
#  -
#    name: LGBMClassifier
#    module: lightgbm
#    params:
#      boosting_type: goss
#      num_leaves: 15
#      n_estimators: 1000
#      max_bin: 255
#      n_jobs: -1
#      random_state: 0
  -
    name: KerasClassifier
    module: keras.wrappers.scikit_learn
    params:
      epochs: 32
      batch_size: 256
    threshold:
#      - 0.081
#      - 0.20
#      - 0.040
#      - 0.043
      - 0.02521418
      - 0.2600453
      - 0.02179153
      - 0.04177151
      - 0.05983936
